title: Page
pages: false
files: true
fields:
  title:
    label: Title
    type:  text

  about:
    label: About
    type:  textarea
    required: true
    validate:
      min: 0
      max: 100
    help: This is your about section. The text here goes before the sentence "These are her selected works and this is her archive." You only get a sentence or two here as the whole section needs to fit on the screen at once.

  selectedWorks:
    label: Selected Works
    type: structure
    style: table
    fields:
      image:
        label: Image
        type: selector
        mode: single
        types:
                - image
        help: Images must be at least 500px and at most 2000px wide
      title:
        label: Title
        type: text
      year:
        label: Year
        type: number

  archive:
    label: Archive
    type: structure
    style: table
    fields:
      image:
        label: Image
        type: selector
        mode: single
        types:
                - image
        help: Images must be at least 500px and at most 2000px wide
      title:
        label: Title
        type: text
      medium:
        label: Medium
        type: text
      year:
        label: Year
        type: number

  contact:
    label: Contact Email
    type: email
